# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 338b76bcef8c75eddfffd28e8ca8ca264631c3becfff21e25634622afb640bcc57363a0b31a63fe0645fe00bddb475825f3c2454ee4500796a67d246bc79cbbe

test:
  secret_key_base: ec7392ecab6cd361ed56f3e0ca4cc5724d25b4fd8e1cdd0da8cf0e8961e6b1b490587694362179103acf99af26d5c454dc951204fe2fabbf12248df864e8170c

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
